name: Update Release Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Execute program
        run: |
          export PYTHONPATH="$PYTHONPATH:$PWD"
          python src/app.py release
        id: execute-program
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: automation
          author_email: action@github.com
          message: 'Update release.json: Added Versions: ${{ steps.execute-program.outputs.ADDED_VERSIONS }}'
          add: 'release.json'